version: '3'

services:
  url-shortener:
    container_name: url-shortener
    build:
      context: ./url-shortener
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
      - elasticsearch
    ports:
      - 4000:4000
    volumes:
      - ./url-shortener:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/prisma
    entrypoint: ["sh", "-c", "npm install && nodemon --watch src --exec 'npm run start:dev'"]
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/db_url_shortener" 

  db:
    container_name: mysql
    image: mysql:8.0.30-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_url_shortener   
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql  

  prisma:
    container_name: prisma
    build:
      context: ./url-shortener/prisma
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
    volumes:
      - /app/prisma  
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/db_url_shortener"    
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  mysql_data:
    driver: local
  es_data:
    driver: local
