version: '3'

services:
  url-shortener:
    build: ./url-shortener
    ports:
      - 4000:4000
    volumes:
      - ./url-shortener:/home/node/app
    entrypoint: sh -c "npm install && npm run start:dev"

  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_url_shortener
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql  
      

  # prisma-studio:
  #     image: node:20-slim
  #     working_dir: /home/node/app
  #     volumes:
  #       - ./url-shortener:/home/node/app
  #     entrypoint: ["sh", "-c", "npm install && npx prisma studio"]
  #     depends_on:
  #       - db

volumes:
  mysql_data:
    driver: local      